import pandas as pd
from pathlib import Path

project_root = Path.cwd()
symbol_dirs = [d for d in project_root.iterdir() if d.is_dir()]
summaries = []

for d in sorted(symbol_dirs):
    try:
        symbol = d.name
        trades_file = d / f"{symbol}_advanced_trade_log.csv"
        equity_file = d / f"{symbol}_advanced_equity_curve.csv"

        trades = pd.read_csv(trades_file)
        equity = pd.read_csv(equity_file)

        total_trades = len(trades)
        win_rate = (len(trades[trades['pnl'] > 0]) / total_trades) * 100 if total_trades else 0
        avg_pnl = trades['pnl'].mean() if total_trades else 0
        max_dd = equity['drawdown'].min() * 100
        final_equity = equity.iloc[-1]['equity']

        summaries.append({
            "symbol": symbol,
            "total_trades": total_trades,
            "win_rate": win_rate,
            "avg_pnl": avg_pnl,
            "max_drawdown": max_dd,
            "final_equity": final_equity
        })
    except Exception:
        continue

html = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Fin-Toro V2 Backtest Index</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #2c3e50; }
        table { border-collapse: collapse; width: 100%; margin-top: 20px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: center; }
        th { background-color: #f5f5f5; }
        tr:hover { background-color: #f9f9f9; }
        a { text-decoration: none; color: #007acc; }
    </style>
</head>
<body>
    <h1>📘 Fin-Toro Strategy Report Index</h1>
    <table>
        <tr>
            <th>Symbol</th>
            <th>Total Trades</th>
            <th>Win Rate (%)</th>
            <th>Avg PnL ($)</th>
            <th>Max Drawdown (%)</th>
            <th>Final Equity ($)</th>
            <th>Report Link</th>
        </tr>
"""

for stat in summaries:
    html += f"""
        <tr>
            <td>{stat['symbol']}</td>
            <td>{stat['total_trades']}</td>
            <td>{stat['win_rate']:.2f}</td>
            <td>{stat['avg_pnl']:.2f}</td>
            <td>{stat['max_drawdown']:.2f}</td>
            <td>{stat['final_equity']:.2f}</td>
            <td><a href="{stat['symbol']}/{stat['symbol']}_advanced_report.html">📄 View</a></td>
        </tr>
    """

html += """
    </table>
    <p><i>Generated by Fin-Toro V2</i></p>
</body>
</html>
"""

(project_root / "index.html").write_text(html.strip())
print("✅ Enhanced index.html saved successfully.")
