# generate_advanced_report.py

import json
import pandas as pd
from weasyprint import HTML
from pathlib import Path

# === Load config ===
with open("config.json") as f:
    config = json.load(f)

symbol = config["symbol"]
outdir = Path(symbol)

# === Load data ===
trades = pd.read_csv(outdir / f"{symbol}_advanced_trade_log.csv", parse_dates=['entry_time', 'exit_time'])
equity = pd.read_csv(outdir / f"{symbol}_advanced_equity_curve.csv", parse_dates=['timestamp'])

# === Summary stats ===
total_trades = len(trades)
win_rate = (len(trades[trades['pnl'] > 0]) / total_trades) * 100 if total_trades else 0
avg_pnl = trades['pnl'].mean() if total_trades else 0
max_drawdown = equity['drawdown'].min() * 100
final_equity = equity.iloc[-1]['equity']

# === HTML content ===
html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{symbol} Advanced Report</title>
    <style>
        body {{ font-family: Arial; margin: 40px; }}
        h1 {{ color: #2c3e50; }}
        table {{ border-collapse: collapse; width: 50%; }}
        th, td {{ border: 1px solid #ccc; padding: 8px; }}
        img {{ width: 100%; max-width: 900px; margin: 20px 0; }}
    </style>
</head>
<body>
    <h1>📘 {symbol} Strategy Report</h1>
    <h2>🧠 Strategy Metadata</h2>
    <ul>
        <li><b>Strategy:</b> {config['strategy']}</li>
        <li><b>Indicators:</b> SMA {config['indicators']['sma']}, EMA {config['indicators']['ema']}</li>
        <li><b>Initial Capital:</b> ${config['capital']}</li>
        <li><b>Stop Loss:</b> {config['stop_loss_pct']*100:.2f}%</li>
        <li><b>Take Profit:</b> {config['take_profit_pct']*100:.2f}%</li>
        <li><b>Max Leverage:</b> {config['max_leverage']}x</li>
    </ul>

    <h2>📊 Summary Stats</h2>
    <table>
        <tr><th>Total Trades</th><td>{total_trades}</td></tr>
        <tr><th>Win Rate</th><td>{win_rate:.2f}%</td></tr>
        <tr><th>Average PnL</th><td>${avg_pnl:.2f}</td></tr>
        <tr><th>Max Drawdown</th><td>{max_drawdown:.2f}%</td></tr>
        <tr><th>Final Equity</th><td>${final_equity:.2f}</td></tr>
    </table>

    <h2>📈 Charts</h2>
    <img src="{symbol}_advanced_equity_chart.png" alt="Equity">
    <img src="{symbol}_advanced_drawdown_chart.png" alt="Drawdown">
    <img src="{symbol}_advanced_pnl_histogram.png" alt="PnL">

    <h2>🔗 Resources</h2>
    <ul>
        <li><a href="{config['repo_link']}">GitHub Repository</a></li>
        <li><a href="{symbol}_advanced_trade_log.csv">Trade Log</a></li>
        <li><a href="{symbol}_advanced_equity_curve.csv">Equity Curve</a></li>
    </ul>

    <p><i>Generated by Fin-Toro Strategy Engine V2</i></p>
</body>
</html>
"""

# === Write report ===
html_path = outdir / f"{symbol}_advanced_report.html"
pdf_path = outdir / f"{symbol}_advanced_report.pdf"

with open(html_path, "w") as f:
    f.write(html)
print(f"✅ HTML report: {html_path}")

HTML(html_path).write_pdf(pdf_path)
print(f"📄 PDF report: {pdf_path}")
